//--------------------------------------------------------------
// all string resource define here
static FS_ResString GFS_ResString [] =
{
	{ FS_T_EML,						"Smart Fox Mailer",			"灵狐电邮"				},
	{ FS_T_Navigate,					"Navigation",				"导航"				},
	{ FS_T_EML_INBOX,					"Server",					"新到邮件"				},
	{ FS_T_RECVBOX,					"LocalBox",					"己收邮件"				},
	{ FS_T_OUTBOX,					"Outbox",					"己发信箱"				},
	{ FS_T_SENDBOX,					"Sendbox",					"发件箱"				},
	{ FS_T_DRAFTBOX,					"DraftBox",					"草稿箱"				},
	{ FS_T_EML_RECV,					"Connect",					"收取邮件"				},
	{ FS_T_DEL_FOLDER,				"Delete Folder",			"清空信箱"				},
	{ FS_T_EML_NEW,					"New",						"新建邮件"				},
	{ FS_T_FALL_BACK,				"Back",						"后退"					},	
	{ FS_T_GO_HOME,					"Page start", 				"跳到页首"					},	
	{ FS_T_GO_END, 					"Page end",					"跳到页尾"					},			
	{ FS_T_EML_NEW_ACCOUNT,			"New Account",				"新建帐户"				},
	{ FS_T_EML_TIP_ACCOUNT_NAME,		"Account Name",				"帐户名"				},
	{ FS_T_EML_TIP_EMAIL_ADDR,		"Email Address",			"邮件地址"				},
	{ FS_T_EML_TIP_IMAP4_ADDR,		"IMAP4 Address",			"IMAP4地址"				},
	{ FS_T_EML_TIP_USER_NAME,			"User Name",				"用户名"				},
	{ FS_T_EML_TIP_PASSWORD,			"Password",					"密码"					},
	{ FS_T_EML_TIP_POP3_PORT,			"POP3 Port",				"POP3端口"				},
	{ FS_T_EML_TIP_IMAP4_PORT,		"IMAP4 Port",				"IMAP4端口"					},
	{ FS_T_EML_TIP_SMTP_PORT,			"SMTP Port",				"SMTP端口"					},
	{ FS_T_EML_TIP_ACCOUNT_TYPE,		"Account Type",				"帐户类型"					},
	{ FS_T_EML_POP3,					"POP3",						"POP3帐户"					},
	{ FS_T_EML_IMAP4,					"IMAP4",					"IMAP4帐户"					},
	{ FS_T_CONFIG_UPDATED,			"Setting updated OK.",		"设置己更新"			},
	{ FS_T_EML_ACT_MGR,				"ActMgr",					"帐户管理"				},
	{ FS_T_NEW,						"New",						"新建"					},
	{ FS_T_NEW_DIR,					"New Dir",					"新建目录"					},
	{ FS_T_RENAME,					"Rename Dir",					"重命名"					},
	{ FS_T_NEW_BMK,					"New Item",					"新建书签"					},
	{ FS_T_ACTIVATE,				"Activate",					"激活帐户"					},
	{ FS_T_NEW_ACT,					"New Account", 				"新建帐户"					},
	{ FS_T_DEL,						"Del",						"删除"					},
	{ FS_T_EML_ACT_EXIST,				"Account already exists!",	"帐户名己存在!"			},
	{ FS_T_CONFIRM_DEL,				"Confirm delete!",			"确认该删除操作?"			},
	{ FS_T_MODIFY_DENY,				"Do not allowed!",			"数据不可修改"			},
	{ FS_T_EML_ACTIVE,				"(Active)",					"(活动)"			},
	{ FS_T_EML_HEAD,					"Head",					"邮件头"			},
	{ FS_T_EML_TEXT,				"Text",						"正文"			},
	{ FS_T_EML_ATTACH,				"Attach",					"附件"			},
	{ FS_T_FROM,						"From",						"发件人"			},
	{ FS_T_TO,						"To",						"收件人"			},
	{ FS_T_CC,						"Cc",						"抄送"			},
	{ FS_T_BCC,						"Bcc",						"暗送"			},
	{ FS_T_EML_ADD_ATTACH,			"Add Attach",				"添加附件"		},
	{ FS_T_EML_EDIT,				"Edit Mail",				"编辑邮件"		},
	{ FS_T_FILE_NOT_EXIST,			"File did not exist or file is empty",		"文件不存在或者文件为空!"		},
	{ FS_T_FILE_TOO_LARGE,			"File too large!",			"文件太大!"		},
	{ FS_T_CONNECTING,				"Connecting",				"连接网络"		},
	{ FS_T_STOP,						"Stop",					"停止"		},
	{ FS_T_AUTH,					"Authorizing",				"身份认证"		},
	{ FS_T_MEMORY_ERR,				"No memory!",				"内存不足!"		},
	{ FS_T_RECVING,					"Retrieving",				"正在接收"		},
	{ FS_T_EML_NO_NEW,				"No new mails!",			"没有新邮件!"		},
	{ FS_T_RECV_OK,					"Retrived ok!",				"接收完成!"		},
	{ FS_T_EML_BAD_MAIL,				"Bad email!", 				"邮件不合法!" 	},
	{ FS_T_RETR,						"Retr",						"接收"			},
	{ FS_T_EML_NOT_EXIST,				"Message did not exist in server!", 		"服务器不存在该邮件!"			},
	{ FS_T_SENDING,					"Sending",					"正在发送"		},
	{ FS_T_SENDOK,					"Send OK!",					"发送成功"		},
	{ FS_T_EML_VIEW,					"Email view",				"查看邮件"		},
	{ FS_T_EML_PICK_ATTACH,			"Pick attach",				"提取附件"		},
	{ FS_T_VIEW,						"View",						"查看"		},
	{ FS_T_DATE,						"Date",						"日期"		},
	{ FS_T_EXPIRY,						"Expiry", 					"超时"		},
	{ FS_T_REPLY_ALL,				"Reply all",				"回复全部"		},
	{ FS_T_EML_SMTP_AUTH, 			"Smtp auth",				"SMTP身份验证"		},
	{ FS_T_SIZE, 						"Size",						"大小"		},
	{ FS_T_EML_TIP_DISP_NAME,			"Display Name", 			"邮箱显示名"		},
	{ FS_T_SYS_SETTING, 				"Sys Setting", 				"系统设置"		},
	{ FS_T_EML_RETR_HEAD,				"Retr head first",			"先接收邮件头"		},
	{ FS_T_EML_MAX_MAIL, 				"Max mail to retr",			"最大接收邮件"		},
	{ FS_T_EML_SERV_BACK,				"Server backup", 			"保留服务器备份"		},
	{ FS_T_EML_TOO_LARGE, 			"Mail too large to retrieve!",				"邮件太大，无法接收!"		},
	{ FS_T_DISCONNECT, 				"Disconnect",								"断开连接"		},
	{ FS_T_NET_INITING,				"Network initializing, try later!",			"网络正在初始化，请稍后再试!"		},
	{ FS_T_NET_UNAVAILABLE,			"Net unavailable!",							"网络不可用!"		},
	{ FS_T_EML_ATTACH_LIST,			"Attach List", 								"附件列表"		},
	{ FS_T_EML_HTML_VIEW, 			"View HTML",								"超文本浏览"		},
	{ FS_T_OPEN,					"Open",										"打开"		},
	{ FS_T_DOC_TYPE,				"Doc Type", 								"文档类型"		},
	{ FS_T_FILE_NAME,				"File Name", 								"文件名"		},
	{ FS_T_EML_REPLY_COPY, 			"Copy msg when reply",						"回复时包含原文"	},
	{ FS_T_EML_SAVE_SEND,				"Save Send mail", 						"保存己发邮件"		},
	{ FS_T_EML_ORIG_MSG_BEGIN, 		"\r\n\r\n======original message======\r\n", 		"\r\n\r\n========邮件原文========\r\n"		},
	{ FS_T_EML_FWD_MSG_BEGIN,			"\r\n\r\n=====below are forward message=====\r\n",	"\r\n\r\n=====下面是转发邮件=====\r\n"		},
	{ FS_T_EML_DEL,					"Delete local",										"本机删除"		},
	{ FS_T_EML_DEL_SVR,				"Delete server", 									"永久删除"		},
	{ FS_T_EML_ACT_EMPTY,				"No email account!", 								"无邮件帐户" 	},
	{ FS_T_EML_ACT_FULL,				"Email account full!",								"邮件帐户己满"	},
	{ FS_T_EML_EDIT_ACCOUNT,			"Edit account",										"编辑帐户"	},
	{ FS_T_EML_ACT_EMPTY_CREATE,		"No email account, Create one?", 					"无邮件帐户,创建一个?"	},
	{ FS_T_OPTION,					"Options",											"选项"	},

	{ FS_T_WEB,						"Smart Fox Explorer",								"灵狐傲游"	},
	{ FS_T_WEB_LOAD_FILE, 			"Load File", 										"装载网页"	},
	{ FS_T_DOWNLOADING, 				"Dowloading", 										"下载数据"	},
	{ FS_T_WEB_CACHE, 				"View Cache", 										"临时缓存"	},
	{ FS_T_PAGE_PROPERTY, 			"Page Property", 										"页面属性"	},
	{ FS_T_UNKNOW_ERR,				"Unknow error",										"未知错误"	},
	{ FS_T_CAN_NOT_SAVE,			"Can not save", 									"无法保存"	},
	{ FS_T_PROTO_HTTP,				"Use http protocol",								"使用HTTP协议"	},
	{ FS_T_PROTO_WSP,					"Use wsp protocol",									"使用WSP协议"	},
	{ FS_T_WEB_BACK,					"Back",												"后退"	},
	{ FS_T_WEB_PREV,					"Forward", 											"前进"	},
	{ FS_T_CONFIRM_EXIT,				"Confirm exit?", 									"确认退出?"	},
	{ FS_T_CONN_SET,					"Connections",										"连接设置"	},
	{ FS_T_WEB_SC,					"Shortcuts",										"快捷键"	},
	{ FS_T_SET_DEFAULT,				"Set Default",										"恢复默认"	},
	{ FS_T_WEB_SC_ENABLE,			"Enable shortcuts",									"启用快捷键"	},
	{ FS_T_CONFIRM_OPERATION,		"Are you sure ?", 									"您是否确认此操作?"	},

	{ FS_T_KEY0,					"Key 0:",										"0键:"	},
	{ FS_T_KEY1,					"Key 1:",										"1键:"	},
	{ FS_T_KEY2,					"Key 2:",										"2键:"	},
	{ FS_T_KEY3,					"Key 3:",										"3键:"	},
	{ FS_T_KEY4,					"Key 4:",										"4键:"	},
	{ FS_T_KEY5,					"Key 5:",										"5键:"	},
	{ FS_T_KEY6,					"Key 6:",										"6键:"	},
	{ FS_T_KEY7,					"Key 7:",										"7键:"	},
	{ FS_T_KEY8,					"Key 8:",										"8键:"	},
	{ FS_T_KEY9,					"Key 9:",										"9键:"	},
	
	{ FS_T_WEB_GENERAL,				"General Option",									"常规设置"	},
	{ FS_T_PLAY_BGSOUND,			"Play Bg Sound",									"播放背景音乐"	},
	{ FS_T_QUICK_START,				"Quick Start >>",										"快速通道>>"	},
	{ FS_T_QUICK_SEARCH,			"Quick Search >>",									"快速搜索>>"	},
	{ FS_T_BAIDU,					"Baidu Search",										"百度一下"	},
	{ FS_T_GOOGLE,					"Google Search",										"Google搜索"	},
	{ FS_T_RECOMMAND,				"Recommand",										"推荐网站"	},
	{ FS_T_CONNECT,					"Connect",											"连接"	},
	{ FS_T_WEB_BMK_TITLE,				"Bookmark title",									"书签标题"	},
	{ FS_T_DIR_NAME,					"Dir Name",											"文件夹名称"	},
	{ FS_T_WEB_BMK_URL,				"Bookmark URL",										"书签网址"	},
	{ FS_T_WEB_DEL_CACHE,				"Clear History",									"清除历史"	},
	{ FS_T_WEB_DEL_COOKIE,			"Clear cookie",										"删除Cookie"	},
	{ FS_T_WEB_USE_CACHE_IMAGE,		"Use cache image file",								"使用缓存图片"	},
	{ FS_T_WEB_CACHE_IMAGE_FIRST_TIP,	"Will reduce flux",									"将减少网络流量"	},
	{ FS_T_WEB_SET_HOME_PAGE_TIP,		"Set home page",									"设置主页"	},
	{ FS_T_SAVE_CONTENT, 				"Save ...",											"保存内容"	},
	{ FS_T_WEB_SAVE_URL,				"Save URL", 										"保存网址"	},
	{ FS_T_WEB_SAVE_PAGE,				"Save page", 										"保存网页"	},
	{ FS_T_SAVE_IMAGE, 					"Save image",										"保存图片"	},
	{ FS_T_SAVE_AUDIO,					"Save audio",										"保存铃声"	},
	{ FS_T_SAVED_TO,					"Saved to",											"己保存到"	},
	{ FS_T_SAVE_FILE_FAILED,				"Save file failed",									"保存文件失败"	},
	{ FS_T_SAVE_FAILED, 				"Save failed.",										"保存失败"	},
	{ FS_T_SAVE_OK, 					"Save successed.", 									"保存成功"	},
	{ FS_T_ROOT_DIR,					"Root Dir",											"根目录"	},
	{ FS_T_NO_IMAGE,					"Page have none images", 							"网页没有包含图片"	},
	{ FS_T_NO_AUDIO,					"Page have none bg sound",							"网页没有背景铃声"	},
	{ FS_T_WEB_HOME_PAGE,				"Home Page",										"主页"	},
	{ FS_T_GOTO_URL,					"Goto URL",											"打开网址"	},
	{ FS_T_WEB_PUSH, 					"Push Message",										"PUSH消息"	},
	{ FS_T_WEB_HISTORY,					"History", 											"历史记录"	},
	{ FS_T_PLS_SETHOMEPAGE,				"Please set a url as homepage", 					"请设置主页地址"	},
	{ FS_T_RECENT_VISIT,				"Recent Visited >>", 								"最近访问的网页>>"	},
	{ FS_T_WEB_URL,						"URL",												"网址"	},
	{ FS_T_GOTO,						"Goto",												"访问"	},
	{ FS_T_WEB_PUSH_PRI,				"Urgency", 											"优先级"	},
	{ FS_T_DEL_ALL,						"Delete All",										"全部删除"	},
	{ FS_T_TYPE,						"Type",												"类型"	},
	{ FS_T_PUSH_SI,						"Service Indication", 								"服务指示"	},
	{ FS_T_PUSH_SL,						"Service Loading",									"服务加载"	},
	{ FS_T_NOT_SUPPORT, 				"Browser not support this feature\n",				"浏览器不支持\n"	},

	{ FS_T_MMS,							"Smart Fox Mms",									"灵狐彩信"	},
	{ FS_T_MMS_TEMPLATE,				"Template",											"彩信模板"	},
	{ FS_T_MMS_NEW,						"New MMS", 											"新建彩信"	},
	{ FS_T_FOLDER_DETAIL,				"Folder Detail",									"信箱详情"	},
	{ FS_T_MMS_EDIT,					"Mms Edit",											"编辑彩信"	},
	{ FS_T_MMS_PREVIEW,					"Preview",											"预览" },
	{ FS_T_ADD_FRAME, 					"Add Frame",										"添加屏幕" },
	{ FS_T_SET_LAYOUT,					"Set Layout",										"布局设置" },
	{ FS_T_ADD_IMAGE,					"Add Image",										"插入图片" },
	{ FS_T_ADD_VIDEO,					"Add Video",										"插入视频" },
	{ FS_T_ADD_AUDIO,					"Add Audio",										"插入音频" },
	{ FS_T_DEL_FRAME,					"Del Frame",										"删除屏幕" },
	{ FS_T_FRAME_NUM,					"Frame: %d",										"第%d帧" },
	{ FS_T_DEL_VIDEO,					"Del Video",										"删除视频" },
	{ FS_T_DEL_AUDIO,					"Del Audio",										"删除音频" },
	{ FS_T_MMS_FRAMES_LIMITED,			"Mms frames limited",								"彩信帧数己达到最大" },
	{ FS_T_FORMAT_MMS_DETAIL,			"Frames(%d/%d), %d KB",								"第%d/%d帧, %d KB" },
	{ FS_T_SET_FRAME_DUR,				"Slide Duration",									"帧持续时间" },
	{ FS_T_MMS_DUR_DESC,				"(Seconds)\n0 for no timer",						"单位为秒\n0为无定时器" },
	{ FS_T_LAYOUT_IMAGE_UP,				"Image on top",										"图片在顶部" },
	{ FS_T_LAYOUT_IMAGE_DN,				"Image on bottom",									"图片在底部" },
	{ FS_T_MMS_VIEW, 					"Mms View",											"查看彩信" },
	{ FS_T_NEXT_FRAME,					"Next Slide", 										"下一帧" },
	{ FS_T_REPLAY,						"Replay",											"重新播放" },
	{ FS_T_MANUAL_PLAY,					"Play manual",										"手动播放" },
	{ FS_T_PREV_FRAME,					"Prev Slide",										"上一帧" },
	{ FS_T_NO_CONTENT,					"No content to save in this slide",					"本页无可保存的内容" },
	{ FS_T_SAVED,						"Saved success.", 									"己保存" },
	{ FS_T_MMS_VIDEO_TIP,				
		"TIP: This frame contains a video. please save it to your mobile and view it by video player.",	
		"提示: 本页包含视频，请从菜单中把视频保存到手机上，再通过视频播放器查看视频内容." },
	{ FS_T_FILE_NOT_SUPPORT,			"File not support",									"文件类型不支持" },
	{ FS_T_MMS_SUBJECT,					"MMS Subject",										"彩信主题" },
	{ FS_T_MMS_TEXT, 					"MMS Text",											"彩信内容" },
	{ FS_T_NO_SUBJECT, 					"No Subject",										"无主题" },
	{ FS_T_DEL_OK,						"Delete Sucess!",									"删除成功!" },
	{ FS_T_LOCATION,					"Location",											"位置" },
	{ FS_T_PHONEBOOK,					"Phonebook", 										"电话本" },
	{ FS_T_ERR_NET_BUSY,				"Net is busy.\nPlease try again later.",			"网络正忙,请稍后再试" },
	{ FS_T_ERR_UNKNOW,					"Unknow error",										"未知错误" },
	{ FS_T_ERR_MEMORY,					"Memory run out", 									"内存不足" },
	{ FS_T_MAX_WEB_TIMER,				"Web timer max value",								"网络定时器最大值" },
	{ FS_T_SET_HOME_PAGE,				"Set as home page",									"设为主页" },
	{ FS_T_MOVE_TO_FOLDER,				"Move to folder",									"移到目录" },
	{ FS_T_INPUT_ADDR, 					"Input recipients pls",								"请输入收件人" },
	{ FS_T_INVALID_ADDR,				"Invalid address", 									"地址不合法" },
	{ FS_T_LIST_FULL, 					"List Full!!",										"列表己满!" },
	{ FS_T_DIR_FULL, 					"Directory num limit!!",							"文件夹个数己满!" },
	{ FS_T_STATUS,						"Status",											"状态" },
	{ FS_T_UNRECV,						"Not retrieve",										"未接收" },
	{ FS_T_UNREAD,						"Unread", 											"未读" },
	{ FS_T_READED,						"Read",												"己读" },
	{ FS_T_AUTO_RECV,					"Auto Retrive", 									"自动接收" },
	{ FS_T_ALLOW_ADS,					"Allow AD", 										"允许广告" },
	{ FS_T_ALLOW_DLV_RPT,				"Allow Delivery Report", 							"允许送达提示" },
	{ FS_T_ALLOW_READ_RPT,				"Send read report",									"发送阅读报告" },
	{ FS_T_SAVE_SEND,					"Save sended MMS", 									"保存己发彩信" },
	{ FS_T_MMS_CENTER,					"MMS Center URL",									"彩信中心地址" },
	{ FS_T_VIEW_SPACE,					"View space",										"查看空间" },
	{ FS_T_ITEMS,						"Items",											"条数" },
	{ FS_T_SPACE,						"Memory",											"占用空间" },
	{ FS_T_SET_UNREAD,					"Set Unread",										"设为未读" },
	{ FS_T_SET_READ,					"Set Read",											"设为己读" },
	{ FS_T_SAVE_AS_TEMPLATE,			"Save as template",									"保存为模板" },
	{ FS_T_AUTO_PLAY,					"Auto Play", 										"自动播放" },
	{ FS_T_MMS_SEND_FORM_TIP,			"separate multi-recipients with comma",				"多个收件人用逗号隔开" },
	{ FS_T_MMS_SEND_CNF,				"Send this message?", 								"是否发送此彩信?" },
	{ FS_T_MMS_TOO_LARGE,				"Mms too larget. can not accept",					"彩信太大，无法接收" },
	{ FS_T_MMS_EXPIRY,					"Mms expiry!",										"彩信己过期" },
	{ FS_T_SPACE_IS_FULL,				
		"Memory is full or item limited, please reclain it.",			
		"空间己满或者记录条数超出限制，请清理空间" },
	{ FS_T_ADV_EDIT,					"Advance Edit", 									"高级编辑" },
	{ FS_T_REQ_DLV_REPORT,				"Req Dlv Report",									"请求送达报告" },
	{ FS_T_CLR_DLV_REPORT,				"Cancel Dlv Report", 								"取消送达报告" },
	{ FS_T_CLR_READ_REPORT,				"Cancel Read Report",								"取消阅读报告" },
	{ FS_T_REQ_READ_REPORT, 			"Req Read Report",									"请求阅读报告" },
	{ FS_T_MMS_READ_REPORT, 			
		"the mms you send to %s was read on %s.\r\n\r\nTo:%s\r\nSubject:%s\r\nid:%s\r\n",
		"你发送给 %s 的彩信已经被接收者阅读。阅读时间为 %s.\r\n\r\n收件人:%s\r\n主题:%s\r\n消息ID:%s\r\n" },
	{ FS_T_MMS_DEL_REPORT, 			
		"the mms you send to %s was delete without read on %s.\r\n\r\nTo:%s\r\nSubject:%s\r\nid:%s\r\n",
		"你发送给 %s 的彩信在阅读前已经被接收者删除。删除时间为 %s.\r\n\r\n收件人:%s\r\n主题:%s\r\n消息ID:%s\r\n" },
	{ FS_T_MMS_DELIVERY_IND,			"The mms was deliveried", 							"彩信己送达" },
	{ FS_T_RE_SMS,						"Reply SMS",										"回复短信" },
	{ FS_T_RE_MMS,						"Reply MMS",										"回复彩信" },
		
	{ FS_T_CHANNEL_LIST, 				"Channel List",										"频道列表" },
	{ FS_T_DCD,							"DCD", 												"快讯" },
	{ FS_T_MORE_CONTENT, 				"more content ...",									"更多内容..." },
	{ FS_T_MAN_UPDATE,					"Update", 											"手动更新" },
	{ FS_T_ADD_CHANNEL,					"Add Channel",										"添加频道" },		
	{ FS_T_DEL_CHANNEL,					"Delete Channel",									"删除频道" },
	{ FS_T_BG_UPDATING,					"Updating now\nPlease wait...",						"开始更新\n请稍候..." },
	{ FS_T_DCD_ON, 						"DCD on/off", 										"启用快讯功能" },
	{ FS_T_DCD_NET_MODE,				"Mode:",											"连接模式:" },
	{ FS_T_DCD_IDLE_DISPLAY,			"idle display", 									"待机显示" },
	{ FS_T_DCD_IDLE_SPEED,				"Speed:", 											"滚动速度:" },
	{ FS_T_ALWAYS_ON,					"always on",										"始终连接" },
	{ FS_T_ALWAYS_OFF,					"always off",										"从不连接" },
	{ FS_T_ROAMING_OFF,					"roaming off",										"国际漫游关闭" },
	{ FS_T_SLOW,						"slow",												"慢" },
	{ FS_T_MID,							"normal",											"中" },
	{ FS_T_QUICK, 						"quick",											"快" },
	{ FS_T_CHANNEL_DETAIL,				"Channel detail",									"频道详情" },
	{ FS_T_SNAPSHOT_LIST,				"Snapshots",										"快照列表" },
	{ FS_T_SEND_BY_MMS,					"Send by mms",										"彩信发送" },
	{ FS_T_DCD_DATA_UPDATED, 			"DCD data is updated",								"快讯数据己更新" },

	{ FS_T_STK_LIST,					"Stocks",											"灵狐证券" },
	{ FS_T_ADD_STOCK,					"Add Stock",										"添加股票" },
	{ FS_T_REAL_TIME,					"Real Time",										"分时走势" },
	{ FS_T_STK_PLS_INPUT,				"Please Input Stock Id",							"请输入股票代码" },
	{ FS_T_INVALID_STK_ID,				"Invalid Stock Id",									"错误的股票代码" },
	{ FS_T_REFRESH_TIME,				"Refresh Time(Sec)", 								"更新频率(秒)" },
	{ FS_T_MARKUP_RATE,					"Markup Rate",										"涨跌幅" },
	{ FS_T_MARKUP_VAL,					"Markup Value",										"涨跌额" },
	{ FS_T_CLOSING_PRICE,				"Closing Price",									"昨收盘" },
	{ FS_T_RANGE_RATE,					"Range Rate", 										"振　幅" },
	{ FS_T_OPENING_PRICE,				"Opening Price",									"今开盘" },
	{ FS_T_HIGHEST_PRICE,				"Highest Price",									"最高价" },
	{ FS_T_LOWEST_PRICE,				"Lowest Price",										"最低价" },
	{ FS_T_CUR_PRICE,					"Newest Price", 									"最新价" },
	{ FS_T_TRADE_QUANTUM,				"Total Quantum", 									"成交量" },	
	{ FS_T_HAND,						"Hand", 											"手" },
	{ FS_T_TRADE_MONEY,					"Total Money", 										"成交额" },
	{ FS_T_TEN_KILO,					"10K", 												"万元" },
	{ FS_T_MOVE_UP,						"Move Top",											"移到顶部" },

	{ FS_T_TIP,						"i: ",						"i: "					},
	{ FS_T_SUCCESS,						"Success !", 										"操作成功" },
	{ FS_T_DEL_IMAGE,					"Del Image",										"删除图片" },
	{ FS_T_MENU,						"Menu",						"菜单"					},
	{ FS_T_EXIT,						"Exit",						"退出"					},
	{ FS_T_SEND,					"Send",						"发送"					},
	{ FS_T_SAVE,					"Save",						"保存"				},
	{ FS_T_SELECT,					"Select",					"选择"					},
	{ FS_T_CANCEL,					"Cancel",					"取消"					},
	{ FS_T_EML_ACT,					"Account",					"帐户管理"				},
	{ FS_T_BACK,						"Back",						"返回"					},
	{ FS_T_EML_TIP_POP3_ADDR,			"POP3 Address",				"POP3地址"				},
	{ FS_T_EML_TIP_SMTP_ADDR,			"SMTP Address",				"SMTP地址"				},
	{ FS_T_MSG,						"Message",					"消息"					},
	{ FS_T_OK,						"OK",						"确定"					},
	{ FS_T_EXIT_WITHOUT_SAVE,		"Exit without save?",		"确定不保存退出?"		},
	{ FS_T_INPUT_ALL_DATA_PLS,		"Input all data please",	"数据输入不完整!"		},
	{ FS_T_EDIT,						"Edit",						"编辑"					},
	{ FS_T_SUBJECT,					"Subject",					"主题"			},
	{ FS_T_LIST_EMPTY,				"List is empty!",			"列表为空!"		},
	{ FS_T_DETAIL,					"Detail",					"详情"		},
	{ FS_T_NET_ERR,					"Network error! Try again please.",			"网络错误!\r\n请重试."		},
	{ FS_T_NET_BUSY, 				"Network busy, please try again later!",			"网络正忙, 请稍候再试!"		},
	{ FS_T_SERVER_ERR,				"Server error!",			"服务器错误!"		},
	{ FS_T_REPLY,					"Reply",						"回复"		},
	{ FS_T_FORWARD,					"Forward",						"转发"		},
	{ FS_T_ABOUT, 					"About",					"关于"		},
	{ FS_T_BLUE_SKY, 					"Blue",					"蓝色天空"		},
	{ FS_T_RED_RECALL, 				"Pink",				"粉红回忆"		},
	{ FS_T_GREEN_GRASS, 				"Green",				"青色草原"		},
	{ FS_T_3D_EFFECT, 				"3D effect",				"3D效果"		},
	{ FS_T_DIAL_FAILED,				"Dial up failed.\nNetwork unavailable!\nPlease make sure your SIM card can access network and check your APN setting",		
	"拨号失败!\n网络功能不可用.\n请确保SIM卡可以访问网络且APN设置正确"		},
	{ FS_T_WEB_REQUEST, 				"Sending request", 									"发送请求"	},
	{ FS_T_PLS_WAITING,				"Please waiting ...", 								"请稍候 ..."	},
	{ FS_T_DOWNLOAD_IMG, 				"Fetch Image",									"下载图片"	},
	{ FS_T_USE_PROXY,				"Use proxy gatway",									"使用代理服务器"	},
	{ FS_T_PROXY_ADDR,			"Proxy address",									"代理服务器地址"	},
	{ FS_T_PROXY_PORT,			"Proxy port",										"代理服务器端口"	},
	{ FS_T_GRAY_CLASSICAL,			"Gray", 									"灰色经典"	},
	{ FS_T_YELLOW_STORM,			"Yellow",										"橙色风暴"	},
	{ FS_T_NONE,					"None",												"无"	},
	{ FS_T_APN,						"APN", 												"接入点"	},
	{ FS_T_USER_NAME, 				"User Name",										"用户名"	},
	{ FS_T_PASSWORD,				"Password",											"密码"	},
	{ FS_T_WEB_DOWN_IMAGE,			"Pictures",											"显示图片"	},
	{ FS_T_REFRESH,					"Refresh",											"刷新"	},
	{ FS_T_FAVORITE,				"Favorites",										"收藏"	},
	{ FS_T_INBOX, 						"Inbox",											"收件箱"	},

	{ FS_T_LOGIN,						"Login",												"登录" },
	{ FS_T_SAVE_PWD,					"Remember Password",							"保存密码" },
	{ FS_T_AUTO_LOGIN,					"Auto Login",										"自动登录" },
	{ FS_T_PLS_INPUT_USER,				"Username empty!",									"请输入用户名" },
	{ FS_T_PLS_INPUT_PWD,				"Password empty!",									"请输入密码" },
	{ FS_T_SETTING,						"Setting",											"设置" },
	{ FS_T_SINA,						"Sina",												"新浪" },
	{ FS_T_TWITTER,						"Twitter",											"推特" },
	{ FS_T_FACEBOOK,					"Facebook",											"脸谱" },
	{ FS_T_MYSPACE,						"Myspace",											"聚友" },
	{ FS_T_ISYNC,						"iSync",											"爱生活" },
	{ FS_T_RSS,							"RSS",												"新闻" },
	{ FS_T_UPDATE,						"Updates",											"最新动态" },
	{ FS_T_SNS_REPLY,					"@Reply",											"关于我的" },
	{ FS_T_COMPOSE,						"Compose",											"推" },
	{ FS_T_FRIENDS,						"Friends",											"朋友" },
	{ FS_T_USER_OR_PASS_ERR,			"User name or password error",						"用户名或密码错误" },
	{ FS_T_SNS_UNBOUND,					"SNS entry unbound",								"微博未绑定" },
	{ FS_T_REGISTER,					"Register",											"注册" },
	{ FS_T_PASSWORD_CHECK,				"Password Again",									"确认密码" },
	{ FS_T_EMAIL,						"Email",											"电子邮件" },
	{ FS_T_PLS_INPUT_PWD,				"Please input Email",								"请输入邮件地址" },
	{ FS_T_PASSWORD_MISMATCH,			"Password mismatch",								"两次输入的密码不一致" },
	{ FS_T_REGISTER_SUCCESS,			"Register Success.",								"注册成功" },
	{ FS_T_USER_ALREADY_EXIST,			"User Name already exist",							"用户名己存在" },
	{ FS_T_MSG_CANNOT_EMPTY,			"Message cannot be empty",								"内容不能为空" },
	{ FS_T_SNS_SAY_SOMETHING,			"Say something(<140)",								"说点什么吧(<140)" },
	{ FS_T_NEXT_PAGE,					"Next Page",										"下一页" },
	{ FS_T_PREV_PAGE,					"Prev Page",										"上一页" },
	{ FS_T_RETWEET,						"Retweet",											"再推" },
	{ FS_T_SYNC_TO,						"Sync to ",									"同步到 " },
	{ FS_T_GO,						"Go",												"打开" },
	{ FS_T_NEWS_FEED,					"News Feed",										"最新动态" },
	{ FS_T_MESSAGES,					"Messages",											"关于我的" },
	{ FS_T_TIMELINE,					"Timeline",											"最新动态" },
	{ FS_T_MENTIONS,					"@Mentions",										"关于我的" },
	{ FS_T_ME,							"@Me",										"关于我的" },
	{ FS_T_WALL,						"Wall",										"关于我的" },
	{ FS_T_PRESS_REFRESH,				"Please Refresh content",				"按 刷新 获取最新动态" },
	{ FS_T_WAIT_RESPONSE,				"Wait Response",									"等待应答" },
	{ FS_T_PHOTO,					"Photograph",									"图片" },
	{ FS_T_NEW_PHOTO,				"New Photo",									"新图片" },
	{ FS_T_SELECT_PHOTO,				"Select Photo",									"选择图片" },
	{ FS_T_UPLOAD_CONFIRM,				"Confirm to upload photo(%d KB)?",					"确认上传图片(%d KB)?" },
	{ FS_T_MSG_CNT_PER_PAGE,			"Page Counts",								"每页显示" },
	{ FS_T_UPLOADING,				"Uploading",											"正在上传" },
	{ FS_T_INPUT_PHOTO_COMMENT,			"Comments for the photo",								"给图片加点注释吧" },
	{ FS_T_BIND,					"Bind",									"同步绑定" },
	{ FS_T_EXTENSION,				"Door",									"增值应用" },
	{ FS_T_MORE,					"More",									"更多" },
	{ FS_T_FEEDBACK,				"Feedback",								"意见反馈" },
	{ FS_T_CONTACT_US,				"Contact Us",								"联系我们" },
	{ FS_T_AVALAA,					"Avalaa China Com. Ltd.\r\nhttp://www.avalaa.com\r\nEmail:support@avalaa.com",
							"腾太科技\r\nhttp://www.avalaa.com\r\n邮箱地址:support@avalaa.com" },
	{ FS_T_ARTICLE,					"Articles",								"文章" },
	{ FS_T_CHANNEL,					"Channels",								"频道" },
	{ FS_T_RECEIVER,				"Reciever",								"接收者" },
	{ FS_T_CONTENT,					"Content",								"内容" },
	{ FS_T_N_YEAR_AGO,				" year(s) ago",							"年前" },
	{ FS_T_N_MONTH_AGO,				" month(s) ago",						"个月前" },
	{ FS_T_N_DAY_AGO,				" day(s) ago",							"天前" },
	{ FS_T_N_HOUR_AGO,				" hour(s) ago",							"小时前" },
	{ FS_T_N_MINUTE_AGO,			" minute(s) ago",						"分钟前" },
	{ FS_T_N_SECOND_AGO,			" second(s) ago",						"秒前" },
	{ FS_T_IMAGE_CACHE,				"Image Cache",							"图片缓存" },
	{ FS_T_VERSION,					"Version",								"版本" },
	{ FS_T_TIMEZONE,				"Time Zone",							"时区" },
	{ FS_T_THEME,					"UI Style",								"界面风格" },
	{ FS_T_LIKE,					"Like",									"喜欢" },
	{ FS_T_FIND_FRIEND,				"Find Friend",							"找朋友" },
	{ FS_T_MALE,					"Male",									"男" },
	{ FS_T_FEMALE,					"Female",								"女" },
	{ FS_T_NO_NEW_DATA,				"No new data",							"没有新数据" },
	{ FS_T_UNKNOW,					"Unknow",								"未知" },
	{ FS_T_FOLLOW,					"Follow",								"添加好友" },
	{ FS_T_UNFOLLOW,				"Unfollow",								"删除好友" },
	{ FS_T_ADD_FRIEND,				"Add Friend",							"添加好友" },
	{ FS_T_UNFRIEND,				"Unfriend",								"删除好友" },
	{ FS_T_SEND_MSG,				"Send Message",							"发送私信" },
	{ FS_T_BINDING,					"Subscribe",							"订阅" },
	{ FS_T_CONTACT,					"Contacts",								"联系人" },
	{ FS_T_ADD_CONTACT,				"Add Contact",							"添加联系人" },
	{ FS_T_MOD_CONTACT,				"Modify",								"修改" },
	{ FS_T_DEL_CONTACT,				"Delete",								"删除" },
	{ FS_T_SEND_EML,				"Send Email",							"发送邮件" },
	{ FS_T_BIND_HOME,				"Bind to iSync",						"绑定到iSync主页" },

	{ FS_T_COPY_RIGHT, 				"\r\nSmart Fox Software Studio\r\nCopyright reserved!",
							"\r\n灵狐软件工作室\r\n版权所有"},

	// the last one
	{ -1,					FS_NULL,					FS_NULL				}	
};
