#ifndef _FS_TIMER_ID_H_
#define _FS_TIMER_ID_H_
enum FS_RES_TIMER_ID
{
	FS_TIMER_ID_WTP = 0x8000,
	FS_TIMER_ID_HTTP,
	FS_TIMER_ID_GUI,
	FS_TIMER_ID_MMS_VIEW,
	FS_TIMER_ID_MMS_AUDIO,
	FS_TIMER_ID_MMS_NET,
	FS_TIMER_ID_MMS_COUNTER,
	FS_TIMER_ID_WEB_COUNTER,
	FS_TIMER_ID_CONN_RETRY,
	FS_TIMER_ID_CONN_TIMEOUT,
	FS_TIMER_ID_DCD_TTL,
	FS_TIMER_ID_DCD_IDLE,
	FS_TIMER_ID_EML_NET,
	FS_TIMER_ID_STOCK,
	FS_TIMER_ID_SNSLIB,
	FS_TIMER_ID_SNSUI,

	FS_TIMER_ID_NUM
};
#endif

