#ifndef _FS_WIDGET_ID_H_
#define _FS_WIDGET_ID_H_
//resource id for widget
enum FS_RES_WGT_ID
{
	FS_W_EmlMainFrm = 0x8000				,
	FS_W_EmlMainMenu						,
	FS_W_EmlActListFrm					,
	FS_W_EmlActMgrMenu					,
	FS_W_EmlActEditFrm					,
	FS_W_EmlEditFrm						,
	FS_W_EmlEditMenu						,
	FS_W_EmlAttachListFrm					,
	FS_W_EmlViewMenu						,
	FS_W_EmlHeadListFrm					,
	FS_W_EmlActTypeMenu					,
	FS_W_EmlActListMenu					,
	FS_W_EmlHeadListMenu				,
	FS_W_EmlRetrProcessFrm			,
	FS_W_EmlActName							,
	FS_W_EmlActType							,
	FS_W_EmlAddr								,
	FS_W_EmlRecvAddr						,
	FS_W_EmlSmtpAddr						,
	FS_W_EmlUserName						,
	FS_W_EmlPassword						,
	FS_W_EmlRecvPort						,
	FS_W_EmlSmtpPort						,
	FS_W_EmlSmtpAuth						,
	FS_W_EmlEditHeadTab					,
	FS_W_EmlEditTextTab					,
	FS_W_EmlEditAttachTab 				,
	FS_W_EmlEditText						,
	FS_W_EmlEditSubject					,
	FS_W_EmlEditAttachList				,
	FS_W_EmlEditBcc						,
	FS_W_EmlEditCc						,
	FS_W_EmlEditTo						,
	FS_W_EmlEditFrom						,
	FS_W_EmlEditDate						,
	FS_W_EmlMainInbox 					,
	FS_W_EmlMainNew						,
	FS_W_EmlMainLocal 					,
	FS_W_EmlMainOutbox					,
	FS_W_EmlMainDraft 					,
	FS_W_Theme3D 							,
	FS_W_EmlSendProcessFrm				,
	FS_W_PRG_TEXT							,
	FS_W_PRG_PRG 							,
	FS_W_EmlDispName						,
	FS_W_EmlActListMainMenu			,
	FS_W_EmlSysSetRetrHead			,
	FS_W_EmlSysSetMaxMail				,
	FS_W_EmlSysSetServBack 			,
	FS_W_EmlSysSettingFrm				,
	FS_W_EmlSysSetMaxMailMenu 		,
	FS_W_ProgressFrm 					,
	FS_W_EmlEditFrmPopUpMenu			,
	FS_W_EmlSysSetReplyCopy			,
	FS_W_EmlSysSetSaveSend			,
	FS_W_EmlSysSetApn				,
	FS_W_EmlSysSetUser				,
	FS_W_EmlSysSetPass				,
	
	FS_W_WebMainFrm					,
	FS_W_WebUrlInput					,
	FS_W_WebWgtSelect 				,
	FS_W_WebMainMenu 					,
	FS_W_WebRecmdListFrm				,
	FS_W_WebRecmdDirFrm				,
	FS_W_WebHistoryListFrm			,
	FS_W_WebViewHistoryFileFrm		,
	FS_W_MsgBoxFrm						,
	FS_W_WebConnSetFrm					,
	FS_W_WebConfigProtoHttp				,
	FS_W_WebConfigProtoWsp				,
	FS_W_WebConfigUseProxy				,
	FS_W_WebConfigProxyAddr				,
	FS_W_WebConfigProxyPort				,
	FS_W_WebConfigApn,
	FS_W_WebConfigUserName,
	FS_W_WebConfigPasswd,
	FS_W_WebConfigMenu					,
	FS_W_WebGeneralSetFrm					,
	FS_W_WebGeneralSetShowTitle			,
	FS_W_WebGeneralSetShowImage			,
	FS_W_WebGeneralSetPlayAudio			,
	FS_W_WebSCSetFrm					,
	FS_W_WebSCEnable,
	FS_W_WebSCSelectMenu,
	FS_W_WebSCNone,
	/* about the web shortcut widget id must be continuous */
	FS_W_WebSCSetKey0					,
	FS_W_WebSCSetKey1					,
	FS_W_WebSCSetKey2					,
	FS_W_WebSCSetKey3					,
	FS_W_WebSCSetKey4					,
	FS_W_WebSCSetKey5					,
	FS_W_WebSCSetKey6					,
	FS_W_WebSCSetKey7					,
	FS_W_WebSCSetKey8					,
	FS_W_WebSCSetKey9					,
	/* end continuous */
	FS_W_WebBookmarkListFrm				,
	FS_W_WebBookmarkDirFrm				,
	FS_W_WebBmkTitle						,
	FS_W_WebBmkUrl						,
	FS_W_WebBmkEditFrm					,
	FS_W_WebCacheFrm						,
	FS_W_WebCacheInfo						,
	FS_W_WebGeneralSetUseCacheImage		,
	FS_W_WebGeneralSetHomePage			,
	FS_W_WebSaveContentMenu				,
	FS_W_WebImageListFrm					,
	FS_W_WebImageViewFrm					,
	FS_W_WebPushListFrm						,
	FS_W_BookmarkListMenu					,
	FS_W_PushMsgListMenu					,

	FS_W_MmsMainFrm							,
	FS_W_MmsInbox							,
	FS_W_MmsOutbox 							,
	FS_W_MmsDraft							,
	FS_W_MmsTemplate 						,
	FS_W_MmsSendbox							,
	FS_W_MmsEditFrm							,
	FS_W_MmsEditMenu						,
	FS_W_MmsViewMenu						,
	FS_W_MmsEditText						,
	FS_W_MmsEditAudio						,
	FS_W_MmsEditImage						,
	FS_W_MmsEditVideo						,
	FS_W_MmsEditImageArea					,
	FS_W_MmsEditFrameList					,
	FS_W_MmsEditFrames						,
	FS_W_MmsEditSubject 					,
	FS_W_MmsEditAddFrame					,
	FS_W_MmsEditDurFrm						,
	FS_W_MmsEditDur							,
	FS_W_MmsEditDurDesc						,
	FS_W_MmsEditLayoutFrm					,
	FS_W_MmsEditLayoutImageUp				,
	FS_W_MmsEditLayoutImageDn				,
	FS_W_MmsViewFrm							,
	FS_W_MmsViewContentListFrm				,
	FS_W_MmsListFrm							,
	FS_W_MmsNew								,
	FS_W_MmsSendFrm							,
	FS_W_MmsSendFrmTo						,
	FS_W_MmsSendFrmCc						,
	FS_W_MmsSendFrmBcc						,
	FS_W_MmsSendFrmSub						,
	FS_W_MmsSendingDlg						,
	FS_W_MmsRecvingDlg						,
	FS_W_WebGeneralSetMaxTimer				,
	FS_W_WebCookieInfo						,
	FS_W_WebBmkSetHome						,
	FS_W_MmsConfigFrm						,
	FS_W_MmsConfigProtoHttp					,
	FS_W_MmsConfigProtoWsp					,
	FS_W_MmsConfigProxyAddr					,
	FS_W_MmsConfigProxyPort					,
	FS_W_MmsConfigApn,
	FS_W_MmsConfigUserName,
	FS_W_MmsConfigPasswd,
	FS_W_MmsConfigMmsCenter					,
	FS_W_MmsConfigAutoRecv					,
	FS_W_MmsConfigAllowAds					,
	FS_W_MmsConfigAllowDlvRpt				,
	FS_W_MmsConfigAllowReadRpt				,
	FS_W_MmsConfigSaveSend					,

	FS_W_DcdMainFrm,
	FS_W_DcdIdleFrm,
	FS_W_DcdDetailFrm,
	FS_W_DcdMainMenu,
	FS_W_DcdSettingFrm,
	FS_W_DcdOnOff,
	FS_W_DcdNetMode,
	FS_W_DcdIdleDisplay,
	FS_W_DcdIdleSpeed,
	FS_W_DcdNetModeSelectMenu,
	FS_W_DcdIdleSpeedSelectMenu,
	FS_W_DcdSnapshotListFrm,
	FS_W_DcdDetailMenu,
	FS_W_DcdSnapshotListMenu,
	FS_W_DcdWaitingFrm,

	FS_W_StkListFrm,
	FS_W_StkAddFrm,
	FS_W_StkAddFrmStkId,
	FS_W_StkConnSetFrm,
	FS_W_StkConfigUseProxy,
	FS_W_StkConfigProxyAddr,
	FS_W_StkConfigProxyPort,
	FS_W_StkConfigApn,
	FS_W_StkConfigUserName,
	FS_W_StkConfigPasswd,
	FS_W_StkConfigRefreshTime,
	FS_W_StkRealTimeFrm,
	FS_W_StkRealTimeImage,
	FS_W_StkDetailFrm,
	FS_W_StkDetailFrmText,
	FS_W_StkUpdateWaitingFrm,
	
	FS_W_SnsLoginFrm,
	FS_W_SnsUserName,
	FS_W_SnsPassword,
	FS_W_SnsSavePwd,
	FS_W_SnsAutoLogin,
	FS_W_SnsListFrm,
	FS_W_SnsSina,
	FS_W_SnsTwitter,
	FS_W_SnsFacebook,
	FS_W_SnsMyspace,
	FS_W_SnsRss,
	FS_W_SnsEntryFrm,
	FS_W_SnsTabUpdate,
	FS_W_SnsTabReply,
	FS_W_SnsUpdateItem,
	FS_W_SnsReplyItem,
	FS_W_SnsTabCompose,
	FS_W_SnsTabFriends,
	FS_W_SnsLoginFrmMenu,
	FS_W_SnsRegisterFrm,
	FS_W_SnsPasswordCheck,
	FS_W_SnsEmail,
	FS_W_SnsRequestingFrm,
	FS_W_SnsComposeTabTweet,
	FS_W_SnsComposeTabAuthor,
	FS_W_SnsComposeTabEdit,
	FS_W_SnsComposeTabImage,
	FS_W_SnsComposeTabCheck,
	FS_W_SnsComposeTabCheckLast = FS_W_SnsComposeTabCheck + 10,
	FS_W_SnsItemMain,
	FS_W_SnsItemMainLast = FS_W_SnsItemMain + 10,
	FS_W_SnsItemUpdates,
	FS_W_SnsItemUpdatesLast = FS_W_SnsItemUpdates + 10,
	FS_W_SnsItemReply,
	FS_W_SnsItemReplyLast = FS_W_SnsItemReply + 10,
	FS_W_SnsFeedback,
	FS_W_SnsFeedbackEdit,
	FS_W_SnsMsgDetailFrm,
	FS_W_SnsSettingFrm,
	FS_W_SnsApn,
	FS_W_SnsProxyAddr,
	FS_W_SnsProxyPort,
	FS_W_SnsUseProxy,
	FS_W_SnsMsgListFrm,
	FS_W_SnsMsgCount,
	FS_W_SnsDisplayImage,
	FS_W_SnsMainMenuFrm,
	FS_W_SnsTabRssArticle,
	FS_W_SnsTabRssChannel,
	FS_W_SnsTabRssBind,
	FS_W_SnsRssFrm,
	FS_W_SnsRssDetailFrm,
	FS_W_SnsRssDetailTitle,
	FS_W_SnsRssDetailMsg,
	FS_W_SnsRssChannelArticleListFrm,
	FS_W_SnsRssCategoryDetailFrm,
	FS_W_SnsRssSecondCategoryFrm,
	FS_W_SnsEmailFrm,
	FS_W_SnsEmlContactSelectFrm,
	FS_W_SnsTabEmlInbox,
	FS_W_SnsTabEmlSend,
	FS_W_SnsTabEmlContact,
	FS_W_SnsTabEmlAccount,
	FS_W_SnsEmlActEmail,
	FS_W_SnsEmlActSmtp,
	FS_W_SnsEmlActPop3,
	FS_W_SnsEmlActUsername,
	FS_W_SnsEmlActPassword,
	FS_W_SnsEmlActBindHome,
	FS_W_SnsEmlDetailSender,
	FS_W_SnsEmlDetailFrm,
	FS_W_SnsEmlSendTo,
	FS_W_SnsEmlSendSubject,
	FS_W_SnsEmlSendContent,
	FS_W_SnsEmlReplyFrm,
	FS_W_SnsEmlDetailSubject,
	FS_W_SnsEmlDetailContent,
	FS_W_SnsImageCache,
	FS_W_SnsSettingTheme,
	FS_W_SnsSettingTimeZone,
	FS_W_SnsFriendsTabEdit,
	FS_W_SnsEmlContactEditFrm,
	FS_W_SnsEmlContactName,
	FS_W_SnsEmlContactEmail,
	FS_W_SnsRssForwardFrm,
	FS_W_SnsEmlAddContact,

	FS_W_Last
};

#endif

